#!/home/yuqinghan/anaconda3/bin/python

from ase.io import read, write
from ase.visualize import view
from ase.calculators.calculator import Calculator
import regex as re
import numpy as np
# import sys
import argparse

def gui_cp2k_dcd(ref_atoms_path='./POSCAR', dcd_path='./*.dcd', aligned_bool=False):
    ref_atoms = read(ref_atoms_path)    # the topo configuration, index==symbol
    trajs = read(dcd_path, index=":", ref_atoms=ref_atoms, aligned=aligned_bool)
    # when use DCD_ALIGNED_CELL key in the CP2K input to write cell info to DCD, one should set aligned=True to get cell info.
    # for Atoms class, one can use Atoms.wrap(**wrap_kw) to wrap positions to unit cell, also see ase.geometry.wrap_positions()
    return trajs

ATOMIC_FORCES_RE = re.compile(
    r'''
    \s+(?P<n_atoms>\d+)\s*\n         # * means zero or many times; + means above element repeat many times
    \si\s=\s+(?P<frame>\d+),\stime\s=\s+(?P<time>\d+\.\d+),\sE\s=\s+(?P<E>[\s-]\d+\.\d+)\n
    (
        \s+(?P<element>\w+)         # w means words or numbers
        \s+(?P<x>[\s-]\d+\.\d+)
        \s+(?P<y>[\s-]\d+\.\d+)
        \s+(?P<z>[\s-]\d+\.\d+)
        \n
    )+
    ''',
    re.VERBOSE                      # allow to use commentary when define regular expression
)

def parse_atomic_forces_list(output_file_path):
    '''reference to Dr. Zhuang Yongbin's cp2kdata package.'''
    with open(output_file_path, 'r') as f:
        output_file = f.read()

    atomic_forces_and_info_list = {}
    for match in ATOMIC_FORCES_RE.finditer(output_file):        # every match is one configuration
        n_atoms = int(match.captures("n_atoms")[0])             # Or use n_atoms = int(match.group(1))
        frame = int(match.captures("frame")[0])
        time = float(match.captures("time")[0])
        E = float(match.captures("E")[0])
        config_forces = []
        for  x, y, z in zip(*match.captures("x", "y", "z")):     # every match is one atom
            config_forces.append([float(x),float(y),float(z)])
        atomic_forces_and_info_list[frame] = {'n_atoms':n_atoms, 'time':time, 'E':E, 'force_config':np.array(config_forces)}

    if atomic_forces_and_info_list:
        return atomic_forces_and_info_list
    else:
        print('===From function "parse_atomic_forces_list" report, No regular expression to match on.===')
        return None

def add_frc_vel_ene_time(forces_file_path, veloc_file_path, export_interval, trajs):
    forces_info = parse_atomic_forces_list(forces_file_path)
    veloc_info = parse_atomic_forces_list(veloc_file_path)
    first_frame = list(forces_info.keys())[0]
    total_frame = len(forces_info.keys())

    if (len(trajs[0]) != forces_info[first_frame]['n_atoms']) or (len(trajs) != total_frame):
        raise Exception(f'''Forces info system may not the same as positions system, 
                    because atoms numbers may not same ({len(trajs[0])}!={forces_info[first_frame]["n_atoms"]}), 
                 or because frames numbers may not same ({len(trajs)}!={total_frame}), CHACK!''')
    cacl_init = Calculator()    # calculator initialize(Instancing)
    for add_frame_number, frame in enumerate(trajs):
        frame.calc = cacl_init
        frame.calc.results['forces'] = forces_info[add_frame_number*export_interval+first_frame]['force_config']
        frame.calc.results['energy'] = forces_info[add_frame_number*export_interval+first_frame]['E']
        frame.info                   = {'time':forces_info[add_frame_number*export_interval+first_frame]['time']}
        frame.set_velocities(veloc_info[add_frame_number*export_interval+first_frame]['force_config'])
    return trajs


if __name__ == '__main__':

    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('path_ref_atoms', type=str, help='path to the reference atoms file')
    parser.add_argument('path_dcd', type=str, help='path to the trajs file with format of dcd generated by CP2K')
    parser.add_argument('aligned_bool', type=str, help='If use DCD_ALIGNED_CELL, set True; use DCD, set False')  
                                        # nargs='+', means one or more parameters are required, and theme are stored in a list
    parser.add_argument('path_frc', type=str, help='path to the force info file')
    parser.add_argument('path_vel', type=str, help='path to the velocity info file')
    parser.add_argument('interval', type=str, help='value of export_interval of MD, including positions forces velocities')
    parser.add_argument('write_bool', type=str, help='If want write fixed trajs to extxyz format, set True; else, set False')

    def str_to_bool(s):
        if s == 'True':
            return True
        elif s == 'False':
            return False
        else:
            raise ValueError("Cannot convert {} to a bool".format(s))

    # script_file_name = sys.argv[0]     # script name, the first argument of command line
    args = parser.parse_args()
    print('===Processing positions.===')
    trajs = gui_cp2k_dcd(ref_atoms_path=args.path_ref_atoms, dcd_path=args.path_dcd, aligned_bool=str_to_bool(args.aligned_bool))
    print('===Processing forces, energies , times and velocities.===')
    trajs_fix = add_frc_vel_ene_time(forces_file_path=args.path_frc, veloc_file_path=args.path_vel, export_interval=int(args.interval), trajs=trajs)
    print('===All Processed done.===')
    view(trajs_fix)
    if str_to_bool(args.write_bool):
        # args.path_frc.
        last_dash_index = args.path_frc.rfind('frc-1')
        extracted_path = args.path_frc[:last_dash_index]
        filename = extracted_path+'fix-MDtrajs.xyz'
        print(f'===Writing extxyz file to {filename}.===')
        write(filename, trajs_fix, format='extxyz')
